name: Vue.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set .env params
      run: |
        echo "VITE_APP_API_URL=https://dishapi-cuczdxckhdh4caev.eastus-01.azurewebsites.net/" > .env
        echo "VITE_APP_BASE_PATH=/" >> .env

    - name: Build the Vue.js app
      run: npm run build

    - name: Deploy to d-i-s-h.github.io
      uses: peaceiris/actions-gh-pages@v3
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        publish_dir: ./dist
        external_repository: d-i-s-h/d-i-s-h.github.io
        publish_branch: main
